php7:
  build: .
  dockerfile: /docker/docker/dockerfile_php_7
  volumes:
    - ./:/var/www/html
    - ./log/:/var/log/apache2/
    - ./docker/php:/usr/local/etc/php
    - ./docker/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
    - ./docker/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
  ports:
    - "80:80"
    - "8080:8080"
  links:
    - mysql


mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    MYSQL_DATABASE: "magento"
    MYSQL_USER: "magento"
    MYSQL_PASSWORD: "magento"
    MYSQL_ROOT_PASSWORD: "magento"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  volumes: 
    - ./mysql:/var/lib/mysql
    - ./docker/mysql:/docker-entrypoint-initdb.d
